### ISSUE TITLE
Dependencies on graphic servers

### ISSUE THREAD

**Issue by dorvan** [waliarubal/Jaya#14]
Hello, there are dependencies on graphic servers, or it's possible to run in kernel mode set?

**Comment by waliarubal** [comment]
Hello @dorvan , I am not that familiar with technalities of Linux or Mac systems but I am assuming you want to know if this app can run in console mode or it just has a UI.

If that's the case then this is an app with GUI only as of now, I haven't thought of console version yet.

Let me know if you have any doubts.

**Comment by waliarubal** [comment]
I hope I have solved your question @dorvan . Please open issue again if you have any queries.
