### ISSUE TITLE
Binding Issues

### ISSUE THREAD

**Issue by waliarubal** [waliarubal/Jaya#15]
Their are a lot of binding warnings appearing in the debug console at run time. Fix those as soon as possible.

**Comment by Splitwirez** [comment]
I took a look at some of those binding errors, and honestly, I'm starting to think some of these binding warnings/errors may be on Avalonia itself, not on us. We should probably reach out to the Avalonia team to confirm that.

**Comment by waliarubal** [comment]
Long back I spoke to @Gillibald regarding some issue I was facing, I don't clearly remember what he said but he mentioned that I should get all of these removed. In fact he was the one to report these issues while he was helping out.

**Comment by waliarubal** [comment]
We are rewriting old codebase, this issue is no more relevant.
