### ISSUE TITLE
add a Plugin store

### ISSUE THREAD

**Issue by furesoft** [waliarubal/Jaya#25]
to easily install plugins with a plugin manager

**Comment by waliarubal** [comment]
This is a nice indeed, I have thought about adding a plugin manager just like Visual Studio.

**Comment by furesoft** [comment]
you can use nuget as repository or host own nuget on a server

**Comment by waliarubal** [comment]
This is interesting approach, are you aware of any nuget client library for pulling up packages from nuget?

**Comment by waliarubal** [comment]
Not thinking to create plugin store as of now. Sticking to XCopy style deployments. May revisit this in future.
