### ISSUE TITLE
double click on folder - navigation

### ISSUE THREAD

**Issue by furesoft** [waliarubal/Jaya#29]
enable double click on a folder in items view to navigate to that folder

**Comment by waliarubal** [comment]
Yeah, that is in pipeline. Earlier it was implemented which I had to comment out to get some things moving. Will be adding up soon enough.

I do have another critical issue to deal with related to Visual Studio designer support for a few Views. Let me know if you are interested in working on it. I'll create an issue and assign it to you @furesoft .

**Comment by furesoft** [comment]
sorry i have to many other projects to work on
