### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by fallenwood** [waliarubal/Jaya#5]
```
System.InvalidOperationException: 'Unable to resolve service for type 'Jaya.Provider.FileSystem.Services.FileSystemService' while attempting to activate 'Jaya.Ui.Services.ProviderService'.'
```
at https://github.com/waliarubal/Jaya/blob/master/Jaya.Shared/Services/ServiceLocator.cs#L100 on startup

**Comment by waliarubal** [comment]
Thanks @fallenwood  for the issue report. I will look at it, was implementing plugable system for file system providers. In middle of it, will fix it.

**Comment by waliarubal** [comment]
@fallenwood please take latest from my repository. The issue has been fixed now, let me know if you see any problems.
