### ISSUE TITLE
DI Broken

### ISSUE THREAD

**Issue by giorgiozoppi** [waliarubal/Jaya#64]
Current DI doesn't load plugins. Could you give it a check as well?

**Comment by waliarubal** [comment]
@giorgiozoppi  I fixed DI yesterday to load plugins, see screenshots below with plugins loaded in various windows.
![Main Window](https://user-images.githubusercontent.com/20422731/83062144-d13bcc00-a07b-11ea-8809-2b25c775c641.png)
![Plugin Manager](https://user-images.githubusercontent.com/20422731/83062191-df89e800-a07b-11ea-9f23-3aca544b4125.png)

Please pull latest code from 'dev' branch, test it at your end and let me know if its not working. Make sure to clean solution before building after pulling the changes.

I am awaiting your response.

**Comment by giorgiozoppi** [comment]
Great job.
