### ISSUE TITLE
New Logo Design

### ISSUE THREAD

**Issue by waliarubal** [waliarubal/Jaya#66]
The current logo for the project doesn't align with the motto of a file system manager. Put in some design ideas and create a new logo which better expresses project's meaning at the very first glance.

![Logo](https://user-images.githubusercontent.com/20422731/83067123-bbcaa000-a083-11ea-8487-efc0360d6f80.png)

**Comment by Splitwirez** [comment]
![](https://i.imgur.com/c0VPIb9.png) here's the initial experiment I showed on Gitter the other day. I'll continue playing around with this and see what I can come up with.

**Comment by giorgiozoppi** [comment]
Good

**Comment by Splitwirez** [comment]
![](https://i.imgur.com/BJTAKH2.png)
Tried the previously-discussed blue folder approach...thoughts?

**Comment by sobirul** [comment]
Do you need a  professional #logo for your business?
Contact me anytime.

**Comment by waliarubal** [comment]
@sobirul yes we need a professional logo but point being since this is an open source project and non profit as of now, will you do it in god faith (free) in exchange for your name (and contact info) in credits, will be free back link to your website.

Seriously speaking, the current logo we have was done by a Fiver freelancer for 500INR and I was not happy about it even after a couple of iterations. So settled with it as is till we get something good which aligns with the meaning of software.

**Comment by Splitwirez** [comment]
So...am I to continue working on logo variants, or is @sobirul taking over on that?

**Comment by sobirul** [comment]
Yes I can do that

**Comment by sobirul** [comment]
But not for free,you have to give me a minimum payment

**Comment by waliarubal** [comment]
@Splitwirez seems like @sobirul is looking for payment. Let's see what is he looking for.

@sobirul what is the minimum payment you are looking for?

**Comment by Splitwirez** [comment]
@waliarubal https://www.fiverr.com/sobir1430 take a look at his/her/its/their fiverr page. Idk if that's the rate he'd/she'd/it'd/they'd be charging us, but the example logos seem...promising, at least IMO.

**Comment by Splitwirez** [comment]
![image](https://user-images.githubusercontent.com/34009058/83278491-b1062d00-a1a1-11ea-9e08-34e422515bf1.png)
I especially like this one - it just...seems right. (I don't know what PixelCloud is, admittedly...)

**Comment by waliarubal** [comment]
[This](https://www.fiverr.com/usashi) is the freelancer I hired earlier for 500 INR to design logo which I was not satisfied with.

Pixel cloud looks good, we never know what will @sobirul  charge us?

**Comment by sobirul** [comment]
Contact me on WhatsApp,
+8801677853856

**Comment by Splitwirez** [comment]
![](https://i.imgur.com/jpHYjdc.png)
@waliarubal How's this?

**Comment by waliarubal** [comment]
what does that gray curvy thing signify?

**Comment by Splitwirez** [comment]
![Icon8-256x](https://user-images.githubusercontent.com/34009058/83572254-3ae22d00-a4f7-11ea-9e8a-e90bce3b5104.png)
Alright, I guess we've got our winning design.

**Comment by waliarubal** [comment]
Nice!!! Great job @Splitwirez .
