### ISSUE TITLE
Include current directory name in window title

### ISSUE THREAD

**Issue by Splitwirez** [waliarubal/Jaya#72]
File Explorer shows the current folder's name in the title of its windows. This feature is extremely useful, since it makes it easier to identify the windows in the ALT+TAB dialog and the Taskbar thumbnail previews. Since we're not File Explorer, we could do something like "My Documents - Jaya", for example, similar to how many web browsers append their names to the end of their windows' titles, after the name of the window's current page.

**Comment by waliarubal** [comment]
Hi @Splitwirez , this feature has been already implemented. See some screenshots below, examine the title bar and see folder names are already there. Let me know if you are referring to something else.

![image](https://user-images.githubusercontent.com/20422731/83506090-4ed06380-a4e4-11ea-9bc8-b12a4f350f0b.png)

![image](https://user-images.githubusercontent.com/20422731/83506154-67407e00-a4e4-11ea-9054-b418d7384143.png)

![image](https://user-images.githubusercontent.com/20422731/83506208-77f0f400-a4e4-11ea-883f-7816697909f6.png)

**Comment by Splitwirez** [comment]
My bad...for some reason I thought this hadn't already been implemented..Just double-checked...I was mistaken. Woops -._.-
