### ISSUE TITLE
Need to skip unsupported drives in FileSystemService.cs

### ISSUE THREAD

**Issue by MikeyFriedChicken** [waliarubal/Jaya#93]
Need to skip unsupported drives in https://github.com/nullvoid-creations/Jaya/blob/dev/src/Jaya.Provider.FileSystem/Services/FileSystemService.cs

Add a try catch like below.  This is because for say mapped google drive stream drives driveInfo.TotalSize will fail the whole process.

                            try
                            {
                                if (!driveInfo.IsReady)
                                    continue;

                                var drive = new DirectoryModel(true);
                                drive.Name = driveInfo.Name;
                                drive.Path = driveInfo.RootDirectory.FullName;
                                drive.Size = driveInfo.TotalSize;
                                model.Directories.Add(drive);
                            }
                            catch (FileNotFoundException fileNotFoundException)
                            {
                                // For example a mapped google file stream will not work (will fail on Total Size)
                                Console.WriteLine($"{driveInfo.Name} is not supported.");
                            }

**Comment by waliarubal** [comment]
Thanks Mike, I'll try it out.

Thanks and Regards
Rubal Walia
(Microsoft Certified Professional)
*Phone:* +91-992-889-3416
*E-mail:* walia.rubal@gmail.com, walia.rubal@rocketmail.com
*Skype:* walia.rubal
*Web:* https://www.waliarubal.com/

**Comment by waliarubal** [comment]
We are rewriting old codebase, this issue is no more relevant.
