### ISSUE TITLE
Wiki regarding build

### ISSUE THREAD

**Issue by maifeeulasad** [waliarubal/Jaya#96]
I was looking for some wiki or readme, to guide me through building this project. But couldn't find any.

I have plan to play with it in Linux-Ubuntu.

**Comment by waliarubal** [comment]
Hello, you can contact me on Skype. Look for ***@***.*** account,
I'll assist.

**Comment by waliarubal** [comment]
Its simple, open is lates Visual Studio on Windows with Avalonia extensions installed. Hit build or run from build toolbar.
